line_style_guide = {
    "Emirates Air": {
        "name": "Emirates Air",
        "color": (220, 36, 31, 255),
        "gen_order": 6,
        "gen_type": "shuttle",
        "station_type": "shuttle",
        "line_type": "triple",
        "name_type": "underground"},

    "DLR": {
        "name": "DLR",
        "color": (0, 175, 173, 255),
        "gen_order": 4,
        "gen_type": "light",
        "station_type": "light",
        "line_type": "double",
        "name_type": "dlr"},

    "Overground": {
        "name": "Overground",
        "color": (239, 123, 16, 255),
        "gen_order": 3,
        "gen_type": "heavy",
        "station_type": "heavy",
        "line_type": "double",
        "name_type": "overground"},

    "London Tram": {
        "name": "London Tram",
        "color": (0, 189, 25, 255),
        "gen_order": 4,
        "gen_type": "tram",
        "station_type": "light",
        "line_type": "double",
        "name_type": "tram"},

    "Elizabeth": {
        "name": "Elizabeth",
        "color": (147, 100, 204, 255),
        "gen_order": 5,
        "gen_type": "secant",
        "station_type": "crossrail",
        "line_type": "double",
        "name_type": "crossrail"},

    "Bakerloo": {
        "name": "Bakerlooo",
        "color": (178, 99, 0, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Central": {
        "name": "Central",
        "color": (220, 36, 31, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Circle": {
        "name": "Circle",
        "color": (255, 211, 41, 255),
        "gen_order": 1,
        "gen_type": "circle",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "District": {
        "name": "District",
        "color": (0, 125, 50, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "H'Smith & City": {
        "name": "H'Smith & City",
        "color": (244, 169, 190, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Jubilee": {
        "name": "Jubilee",
        "color": (161, 165, 167, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Metropolitan": {
        "name": "Metropolitan",
        "color": (155, 0, 88, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Northern": {
        "name": "Northern",
        "color": (0, 0, 0, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Picadilly": {
        "name": "Picadilly",
        "color": (0, 25, 168, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Victoria": {
        "name": "Victoria",
        "color": (0, 152, 216, 255),
        "gen_order": 1,
        "gen_type": "secant",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
    "Waterloo & City": {
        "name": "Waterlooo & City",
        "color": (147, 206, 186, 255),
        "gen_order": 2,
        "gen_type": "shuttle",
        "station_type": "underground",
        "line_type": "single",
        "name_type": "underground"},
}