crossrail = [
    ['Reading', 'Twyford', 'Maidenhead', 'Taplow', 'Burnham', 'Slough', 'Langley', 'Iver', 'West Drayton', 'Hayes & Harlington', 'Southall',
     'Hanwell', 'West Ealing', 'Ealing Broadway', 'Acton Main Line', 'Old Oak Common', 'Paddington', 'Bond Street', 'Tottenham Court Road',
     'Farringdon', 'Liverpool Street', 'Whitechapel', 'Canary Wharf', 'Custom House', 'Woolwich', 'Abbey Wood', 'Stratford', 'Maryland',
     'Forest Gate', 'Manor Park', 'Ilford', 'Seven Kings', 'Goodmayes', 'Chadwell Heath', 'Romford', 'Gidea Park', 'Harold Wood', 'Brentwood',
     'Shenfield'], [], []]

overground = [
    ['Acton Central', 'South Action', 'Gunnersbury', 'Kew Gardens', 'Richmond', 'Harlesden', 'Stonebridge Park', 'Wembley Central', 'North Wembley',
     'South Kenton', 'Kenton', 'Harrow & Wealdstone', 'Headstone Lane', 'Hatch End', 'Carpenders Park', 'Bushey', 'Watford High Street',
     'Watford Junction', "Shepherd's Bush", 'Kensington (Olympia)', 'West Brompton', 'Imperial Wharf', 'Clapham Junction', 'Willesden Junction',
     'Kensal Green', "Queen's Park", 'Kilburn High Road', 'South Hampstead', 'Euston', 'Kensal Rise', 'Brondesbury Park', 'Brondesbury',
     'West Hampstead', 'Finchley Road & Frognal', 'Hampstead Heath', 'Gospel Oak', 'Upper Holloway', 'Crouch Hill', 'Harringay Green Lanes',
     'South Tottenham', 'Blackhorse Road', "Walthamstow Queen's Road", 'Leyton Midland Road', 'Leytonstone High Road', 'Wanstead Park',
     'Woodgrange Park', 'Barking', 'Kentish Town West', 'Camden Road', 'Caledonian Road & Barnsbury', 'Highbury & Islington', 'Canonbury',
     'Dalston Kingsland', 'Hackney Central', 'Homerton', 'Hackney Wick', 'Stratford', 'Dalston Junction', 'Haggerston', 'Hoxton',
     'Shoreditch High Street', 'Whitechapel', 'Shadwell', 'Wapping', 'Rotherhithe', 'Canada Water', 'Surrey Quays', 'New Cross', 'New Cross Gate',
     'Brockley', 'Honor Oak Park', 'Forest Hill', 'Sydenham', 'Crystal Palace', 'Penge West', 'Anerley', 'Norwood Junction', 'West Croydon',
     'Queens Road Peckham', 'Peckham Rye', 'Denmark Hill', 'Clapham High Street', 'Wandsworth Road', 'Liverpool Street', 'Bethnal Green',
     'Cambridge Heath', 'London Fields', 'Hackney Downs', 'Clapton', 'St. James Street', 'Walthamstow Central', 'Wood Street', 'Highams Park',
     'Chingford', 'Rectory Road', 'Stoke Newington', 'Stamford Hill', 'Seven Sisters', 'Bruce Grove', 'White Hart Lane', 'Silver Street',
     'Edmonton Green', 'Bush Hill Park', 'Enfield Town', 'Southbury', 'Turkey Street', 'Theobalds Grove', 'Cheshunt', 'Romford', 'Emerson Park',
     'Upminster'],
    ['Primrose Hill', 'Hythe Road', 'Old Oak Common Lane', 'Renwick Road', 'Barking Riverside', 'Thamesmead', 'Abbey Wood', 'Greenford',
     'South Greenford', 'Castle Bar Park', 'Drayton Green', 'West Ealing', 'Harlesden', 'Lionel Road', 'Hythe Road', 'Neasden', 'Brent Cross'], []]

tram = [['Addington Village', 'Addiscombe', 'Ampere Way', 'Arena', 'Avenue Road', 'Beckenham Junction', 'Beckenham Road', 'Beddington Lane',
               'Belgrave Walk', 'Birkbeck', 'Blackhorse Lane', 'Centrale', 'Church Street', 'Coombe Lane', 'Dundonald Road', 'East Croydon',
               'Elmers End', 'Fieldway', 'George Street', 'Gravel Hill', 'Harrington Road', "King Henry's Drive", 'Lebanon Road', 'Lloyd Park',
               'Merton Park', 'Mitcham', 'Mitcham Junction', 'Morden Road', 'New Addington', 'Phipps Bridge', 'Reeves Corner', 'Sandilands',
               'Therapia Lane', 'Waddon Marsh', 'Wandle Park', 'Wellesley Road', 'West Croydon', 'Wimbledon', 'Woodside'],
              ['Wimbledon Chase', 'South Merton', 'Morden South', 'St. Helier', 'Sutton Common', 'West Sutton', 'Sutton', 'South Wimbledon',
               'Colliers Wood'], []]

dlr = [
    ['Abbey Road', 'All Saints', 'Bank', 'Beckton', 'Beckton Park', 'Blackwall', 'Bow Church', 'Canary Wharf', 'Canning Town', 'Crossharbour',
     'Custom House for ExCeL', 'Cutty Sark for Maritime Greenwich', 'Cyprus', 'Deptford Bridge', 'Devons Road', 'East India', 'Elverson Road',
     'Gallions Reach', 'Greenwich', 'Heron Quays', 'Island Gardens', 'King George V', 'Langdon Park', 'Lewisham', 'Mudchute', 'Pontoon Dock',
     'Poplar', 'Prince Regent', 'Pudding Mill Lane', 'Royal Albert', 'Royal Victoria', 'Shadwell', 'South Quay', 'Star Lane', 'Startford',
     'Stratford High Street', 'Stratford International', 'Tower Gateway', 'West Ham', 'West India Quay', 'West Silvertown', 'Westferry',
     'Woolwich Arsenal'], ['Thames Wharf', 'Beckton Riverside', 'Thamesmead Central'], []]

underground = [
    ['Acton Town', 'Aldgate', 'Aldgate East', 'Alperton', 'Amersham', 'Angel', 'Archway', 'Arnos Grove', 'Arsenal', 'Baker Street', 'Balham', 'Bank',
     'Barbican', 'Barking', 'Barkingside', 'Barons Court', 'Battersea Power Station', 'Bayswater', 'Becontree', 'Belsize Park', 'Bermondsey',
     'Bethnal Green', 'Blackfriars', 'Blackhorse Road', 'Bond Street', 'Borough', 'Boston Manor', 'Bounds Green', 'Bow Road', 'Brent Cross',
     'Brixton', 'Bromley-by-Bow', 'Buckhurst Hill', 'Burnt Oak', 'Caledonian Road', 'Camden Town', 'Canada Water', 'Canary Wharf', 'Canning Town',
     'Cannon Street', 'Canons Park', 'Chalfont & Latimer', 'Chalk Farm', 'Chancery Lane', 'Charing Cross', 'Chesham', 'Chigwell', 'Chiswick Park',
     'Chorleywood', 'Clapham Common', 'Clapham North', 'Clapham South', 'Cockfosters', 'Colindale', 'Colliers Wood', 'Covent Garden', 'Croxley',
     'Dagenham East', 'Dagenham Heathway', 'Debden', 'Dollis Hill', 'Ealing Broadway', 'Ealing Common', "Earl's Court", 'East Acton', 'East Finchley',
     'East Ham', 'East Putney', 'Eastcote', 'Edgware', 'Edgware Road', 'Elephant & Castle', 'Elm Park', 'Embankment', 'Epping', 'Euston',
     'Euston Square', 'Fairlop', 'Farringdon', 'Finchley Central', 'Finchley Road', 'Finsbury Park', 'Fulham Broadway', 'Gants Hill',
     'Gloucester Road', 'Golders Green', 'Goldhawk Road', 'Goodge Street', 'Grange Hill', 'Great Portland Street', 'Greenford', 'Green Park',
     'Gunnersbury', 'Hainault', 'Hammersmith', 'Hampstead', 'Hanger Lane', 'Harlesden', 'Harrow & Wealdstone', 'Harrow-on-the-Hill', 'Hatton Cross',
     'Hendon Central', 'High Barnet', 'Highbury & Islington', 'Highgate', 'High Street Kensington', 'Hillingdon', 'Holborn', 'Holland Park',
     'Holloway Road', 'Hornchurch', 'Hounslow Central', 'Hounslow East', 'Hounslow West', 'Hyde Park Corner', 'Ickenham', 'Kennington',
     'Kensal Green', 'Kensington (Olympia)', 'Kentish Town', 'Kenton', 'Kew Gardens', 'Kilburn', 'Kilburn Park', 'Kingsbury',
     "King's Cross St. Pancras", 'Knightsbridge', 'Ladbroke Grove', 'Lambeth North', 'Lancaster Gate', 'Latimer Road', 'Leicester Square', 'Leyton',
     'Leytonstone', 'Liverpool Street', 'London Bridge', 'Loughton', 'Maida Vale', 'Manor House', 'Mansion House', 'Marble Arch', 'Marylebone',
     'Mile End', 'Mill Hill East', 'Monument', 'Moorgate', 'Moor Park', 'Morden', 'Mornington Crescent', 'Neasden', 'Newbury Park', 'Nine Elms',
     'North Acton', 'North Ealing', 'North Greenwich', 'North Harrow', 'North Wembley', 'Northfields', 'Northolt', 'Northwick Park', 'Northwood',
     'Northwood Hills', 'Notting Hill Gate', 'Oakwood', 'Old Street', 'Osterley', 'Oval', 'Oxford Circus', 'Paddington', 'Park Royal',
     'Parsons Green', 'Perivale', 'Piccadilly Circus', 'Pimlico', 'Pinner', 'Plaistow', 'Preston Road', 'Putney Bridge', "Queen's Park", 'Queensbury',
     'Queensway', 'Ravenscourt Park', 'Rayners Lane', 'Redbridge', "Regent's Park", 'Richmond', 'Rickmansworth', 'Roding Valley', 'Royal Oak',
     'Ruislip', 'Ruislip Gardens', 'Ruislip Manor', 'Russell Square', "St. James's Park", "St. John's Wood", "St. Paul's", 'Seven Sisters',
     "Shepherd's Bush", "Shepherd's Bush Market", 'Sloane Square', 'Snaresbrook', 'South Ealing', 'South Harrow', 'South Kensington', 'South Kenton',
     'South Ruislip', 'South Wimbledon', 'South Woodford', 'Southfields', 'Southgate', 'Southwark', 'Stamford Brook', 'Stanmore', 'Stepney Green',
     'Stockwell', 'Stonebridge Park', 'Stratford', 'Sudbury Hill', 'Sudbury Town', 'Swiss Cottage', 'Temple', 'Theydon Bois', 'Tooting Bec',
     'Tooting Broadway', 'Tottenham Court Road', 'Tottenham Hale', 'Totteridge & Whetstone', 'Tower Hill', 'Tufnell Park', 'Turnham Green',
     'Turnpike Lane', 'Upminster', 'Upminster Bridge', 'Upney', 'Upton Park', 'Uxbridge', 'Vauxhall', 'Victoria', 'Walthamstow Central', 'Wanstead',
     'Warren Street', 'Warwick Avenue', 'Waterloo', 'Watford', 'Wembley Central', 'Wembley Park', 'West Acton', 'West Brompton', 'West Finchley',
     'West Ham', 'West Hampstead', 'West Harrow', 'West Kensington', 'West Ruislip', 'Westbourne Park', 'Westminster', 'White City', 'Whitechapel',
     'Willesden Green', 'Willesden Junction', 'Wimbledon', 'Wimbledon Park', 'Wood Green', 'Wood Lane', 'Woodford', 'Woodside Park'],
    ['Aldgate East', 'Aldwych', 'Alexandra Palace', 'Aylesbury', 'Beckton', 'Blake Hall', 'Brill', 'British Museum', 'Brixton', 'Brockley Hill',
     'Brompton Road', 'Brondesbury', 'Bull and Bush', 'Bushey', 'Bushey Heath', 'Camberwell', 'Cannon Hill', 'Cannon Street', 'Carpenders Park',
     'Castle Hill (Ealing Dean)', 'Charing Cross', 'Cheam', 'City Road', 'Clerkenwell', 'Collingwood Road', 'Cranley Gardens', 'Cricklewood',
     'Crouch End', 'Custom House', 'Denham', 'Down Street', 'Drayton Park', "Earl's Court", 'Elm Farm', 'Elm Grove', 'Elstree South', 'Emlyn Road',
     'Essex Road', 'Fenchurch Street', 'Finchley Road', 'Goodge Street', 'Gower Street', 'Granborough Road', 'Great Missenden', 'Hammersmith',
     'Hammersmith (Grove Road)', 'Hampstead', 'Hanwell', 'Harefield Road', 'Harringay', 'Harrow Road', 'Hatch End', 'Hayes', 'Headstone Lane',
     'Heathfield Terrace', 'Highgate', 'Hillingdon', 'Holborn', 'Hornsey', 'Hounslow Town', 'Hyde Park Corner', 'Kennington Cross', 'Kilburn',
     'King William Street', "King's Cross St Pancras", 'Lambeth Road', 'Langley', 'Leicester Square', 'Leigh-on-Sea', 'Lewisham', 'London Bridge',
     "Lord's", 'Lorn Road', 'Lothbury', 'Ludgate Circus', 'Maida Vale', 'Mansion House', 'Marble Arch', 'Mark Lane', 'Marlborough Road',
     'Merton Park', 'Mill Hill (The Hale)', 'Millwall', 'Muswell Hill', 'New Cross', 'New Cross Gate', 'North End', 'North Greenwich', 'North Weald',
     'Northfields & Little Ealing', 'Ongar', 'Osterley & Spring Grove', 'Oxford Street', 'Paddenswick Road', 'Park Royal & Twyford Abbey',
     'Preston Road', 'Quainton Road', 'Rotherhithe', 'Rylett Road', 'Shadwell', "Shepherd's Bush", 'Shoeburyness', 'Shoreditch', 'Silvertown',
     'Slough', 'South Acton', 'South Harrow', 'South Kentish Town', 'South Morden', 'Southall', 'Southend Central', "St George's Circus",
     'St Katharine Docks', "St Mary's (Whitechapel Road)", 'Stoke Mandeville', 'Stroud Green', 'Surrey Docks', 'Surrey Docks North', 'Surrey Quays',
     'Sutton', 'Sutton Common', 'Swiss Cottage', 'The Grove', 'Tower of London', 'Trafalgar Square', 'Turnham Green', 'Uxbridge', 'Uxbridge Road',
     'Verney Junction', 'Victoria', 'Waddesdon', 'Waddesdon Road', 'Walthamstow Wood Street', 'Walworth', 'Wapping', 'Waterloo', 'Waterloo',
     'Watford Central', 'Watford High Street', 'Watford Junction', 'Wendover', 'West Drayton', 'West End', 'Westbourne Park', 'Westcott',
     'White City', 'Windsor', 'Winslow Road', 'Wood Green', 'Wood Lane', 'Wood Siding', 'Woolwich Arsenal', 'Wotton', 'York Road'],
    [["Mill Hill Park"], None, ["Commercial Road"], ["Perivale-Alperton"], ["Amersham", "Amersham & Chesham Bois"], None,
     ["Archway Tavern", "Highgate", "Archway (Highgate)", "Highgate (Archway)"], ["Bowes Road"], ["Gillespie Road", "Arsenal (Highbury Hill)"], None,
     None, ["City", "Lombard Street"], ["Aldersgate Street", "Aldersgate", "Aldersgate & Barbican"], None, None, None, ["Battersea"],
     ["Bayswater", "Bayswater (Queen's Road) & Westbourne Grove", "Bayswater (Queen's Road)", "Bayswater (Queensway)"], ["Gale Street"], ["Belsize"],
     None, ["Bethnal"], None, None, ["Davies Street", "Selfridge's"], None, ["Boston Road"], ["Brownlow Road"], None, ["Woodstock", "Brent"], None,
     ["Bromley"], None, ["Sheaves Hill", "Orange Hill", "Deansbrook", "Burnt Oak", "Burnt Oak (Watling)"], ["Barnsbury"], ["Camden Road"], None, None,
     None, None, ["Canons Park (Edgware)"], ["Chalfont Road"], ["Adelaide Road"], ["Chancery Lane", "Chancery Lane (Grays Inn)"],
     ["Trafalgar Square", "Charing Cross", "Charing Cross (Strand)", "Strand"], None, None, ["Acton Green", "Chiswick Park & Acton Green"],
     ["Chorley Wood", "Chorley Wood & Chenies", "Chorley Wood"], None, ["Clapham Road"], ["Nightingale Lane"], ["Trent Park"], None, None, None,
     ["Croxley Green"], ["Dagenham"], ["Heathway"], ["Chigwell Road", "Chigwell Lane"], None, None, ["Ealing Common", "Ealing Common and West Acton"],
     None, None, None, None, None, None, None, None, None, None,
     ["Charing Cross", "Embankment", "Charing Cross (Embankment)", "Charing Cross", "Charing Cross Embankment"], None, ["Melton Street"],
     ["Gower Street"], None, ["Farringdon Street", "Farringdon & High Holborn"], ["Finchley & Hendon", "Finchley", "Finchley (Church End)"], None,
     None, ["Walham Green"], ["Ilford North", "Cranbrook"], ["Brompton (Gloucester Road)"], None, None, ["Tottenham Court Road"], None,
     ["Portland Road", "Great Portland Street", "Great Portland Street & Regent's Park"], None, ["Dover Street"], ["Brentford Road"], None, None,
     ["Heath Street"], None, None, ["Harrow"], ["Harrow"], None, None, None, ["Highbury"], None, ["Kensington"],
     ["Hillingdon", "Hillingdon (Swakeleys)"], ["Holborn", "Holborn (Kingsway)"], ["Lansdown Road"], ["Holloway"], None, ["Heston Hounslow"],
     ["Hounslow Town"], ["Hounslow Barracks"], None, None, ["New Street"], None, ["Kensington", "Kensington (Addison Road)"], None, None, None,
     ["Kilburn and Brondesbury"], None, None,
     ["King's Cross", "King's Cross & St. Pancras", "King's Cross", "King's Cross for St. Pancras", "King's Cross for St. Pancras"],
     ["Sloane Street"], ["Notting Hill", "Notting Hill & Ladbroke Grove", "Ladbroke Grove (North Kensington)"],
     ["Kennington Road", "Westminster Bridge Road"], ["Westbourne"], None, ["Cranbourn Street"], ["Low Leyton"], None, ["Bishopsgate"], None, None,
     ["Elgin Avenue"], None, None, None, ["Lisson Grove", "Marylebone", "Great Central"], None, ["Mill Hill", "Bittacy Hill"],
     ["King William Street", "East Cheap"], ["Moorgate Street"], ["Sandy Lodge", "Moor Park & Sandy Lodge"], ["North Morden"], ["Seymour Street"],
     ["Kingsbury & Neasden", "Neasden & Kingsbury"], None, None, None, None, None, None, None, ["Northfield Halt", "Northfields & Little Ealing"],
     None, ["Northwick Park & Kenton"], None, None, None, ["East Barnet", "Merryhills", "Enfield West", "Enfield West (Oakwood)"], None,
     ["Osterley & Spring Grove"], ["Kennington Oval", "The Oval"], None, ["Paddington (Praed Street)", "Paddington (Bishop's Road)"],
     ["Park Royal & Tywford Abbey", "Park Royal", "Park Royal (Hanger Hill)"], None, ["Perivale Hill"], None, None, None, None, None,
     ["Putney Bridge & Fulham", "Putney Bridge & Hurlingham"], ["Queen's Park (West Kilburn)"], None, ["Queen's Road"], ["Shaftesbury Road"], None,
     ["Ilford West", "Red House"], None, None, None, None, None, None, None, None, None, None, ["Acacia Road"], ["Newgate Street", "Post Office"],
     None, None, ["Shepherd's Bush"], None, ["Snaresbrook & Wanstead"], None, None, None, None,
     ["Northolt Junction", "South Ruislip & Northolt Junction"], ["Merton Grove", "South Wimbledon", "South Wimbledon (Merton)"],
     ["George Lane", "South Woodford (George Lane)"], None, ["Chase Side"], None, None, None, None, None, None, None, None, None, None, None,
     ["Theydon"], ["Trinity Road (Tooting Bec)"], None, ["Oxford Street"], None, ["Totteridge"], ["Tower of London", "Mark Lane"], None, None,
     ["Ducketts Green", "Harringay"], None, None, None, None, None, None, None, None, None, ["Euston Road"], ["Warrington Crescent"], None, None,
     ["Sudbury", "Sudbury & Wembley", "Wembley for Sudbury"], None, None, ["Richmond Road"], None, ["West Ham", "West Ham (Manor Road)"], None, None,
     ["North End (Fulham)"], ["Ruislip & Ickenham", "West Ruislip for Ickenham"], None, ["Westminster Bridge"], None, ["Whitechapel (Mile End)"],
     None, None, None, None, ["Lordship Lane"], None, None,
     ["Torrington Park, Woodside", "Woodside Park for North Finchley", "Woodside Park and North Finchley for Woodside Garden Suburb"]]]

airports = [['London City Airport'], ['Heathrow Terminals 2 & 3', 'Heathrow Terminal 4', 'Heathrow Terminal 5']]